### ISSUE TITLE
Cannot run the action

### ISSUE THREAD

**Issue by oldking139** [slavcodev/coverage-monitor-action#245]
> We have detect this problem in both github.com repo and Github enterprise server with self-hosted runner

When we try to run the code coverage test on our PR (not the PR from dependabot but from other developers), we facing some issue, the workflow exit with error.
```
Run slavcodev/coverage-monitor-action@v1
  with:
    github_token: ***
    coverage_path: logs/clover.xml
    coverage_format: auto
    threshold_alert: 50
    threshold_warning: 90
    threshold_metric: lines
    check: true
    status_context: Coverage Report
    comment: true
    comment_context: Coverage Report
    comment_mode: replace
    comment_footer: true
Error: ENOENT: no such file or directory, open '/home/runner/work/littlelink/littlelink/logs/clover.xml'
```

The workflow config is:
```
name: Code coverage CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "logs/clover.xml"
```
