### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by islasjuanp** [slavcodev/coverage-monitor-action#250]
I'm trying to integrate this action into a public repository, but I receive this error when creating a PR. 

![Captura de pantalla 2023-03-31 a la(s) 14 37 19](https://user-images.githubusercontent.com/8229113/229191100-a8c243b7-3985-4bca-900d-2a1550cdee30.png)

Based on the examples in the README file, I assumed that the action doesn't require extra permission. 
Do you know if there is anything that I need to configure from my account? 

**Update:**
The action works with the following permissions

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: write 
          checks: write
          pull-requests: write 
          actions: read 
          statuses: write 
```
Do you know which of these permissions are not necessary?

**Comment by szikszail** [comment]
I experimented a bit and for me this was the minimal set of permissions needed:
```yaml
permissions:
  contents: read
  pull-requests: write
  statuses: write
```
